In [1]:
%matplotlib inline

from matplotlib import pyplot as plt
import pandas as pd
import numpy as np

oldNpRules = np.seterr(all='warn')

In [2]:
foursquareLDA6 = pd.read_csv('featuresSingapore/Foursquare/venueCategoriesLDA6Features.csv', index_col="_id")
foursquareLDA6.head()

ftopic_0  ftopic_1  ftopic_2  ftopic_3  \
_id                                                                        
15715d4a6ce45df597dfa36d7a29dd3e  0.002083  0.139462  0.078715  0.627223   
70467a1614f271f06f2637c1b10e163e  0.000024  0.191960  0.000900  0.007175   
3a50eac12596fd1e6b54abeccbab98ad  0.000333  0.629062  0.012583  0.006919   
9a5e6a840aba8249f1a0f2a38bbe200e  0.002083  0.139462  0.078715  0.627223   
3a68e91b400be1a634e75ccdcfc656a6  0.000531  0.556994  0.169057  0.011043   

                                  ftopic_4  ftopic_5  
_id                                                   
15715d4a6ce45df597dfa36d7a29dd3e  0.115240  0.037278  
70467a1614f271f06f2637c1b10e163e  0.742739  0.057202  
3a50eac12596fd1e6b54abeccbab98ad  0.205120  0.145982  
9a5e6a840aba8249f1a0f2a38bbe200e  0.115240  0.037278  
3a68e91b400be1a634e75ccdcfc656a6  0.252864  0.009510

In [3]:
facebookAnswers = pd.read_csv('SingaporeGroundTruth.csv', encoding='latin1', index_col="row ID")
facebookAnswers.head()

/nix/store/n16wpgk37iwnl7f9c8g6c5c8szr4mk4k-python3.5-pandas-0.17.1/lib/python3.5/site-packages/pandas/core/format.py:2087: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e8).any()
/nix/store/n16wpgk37iwnl7f9c8g6c5c8szr4mk4k-python3.5-pandas-0.17.1/lib/python3.5/site-packages/pandas/core/format.py:2088: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) &
/nix/store/n16wpgk37iwnl7f9c8g6c5c8szr4mk4k-python3.5-pandas-0.17.1/lib/python3.5/site-packages/pandas/core/format.py:2089: RuntimeWarning: invalid value encountered in greater
  (abs_vals > 0)).any()


realAge  gender  ageGroup  \
row ID                                                        
d0cc2d6caf6eb55ccf606770f24df2b5      NaN  female       NaN   
eb4e2aa0bf687227821b17cfcd5365e3      NaN  female       NaN   
acfb8e93139fe820996b27ee3c6bc9db      NaN    male  AGE10_20   
ea251951bd3c7667daf214e8efa92f4e      NaN  female       NaN   
f8f7b497ad8167535345bfc3d59d6aaa      NaN  female       NaN   

                                                                          education  \
row ID                                                                                
d0cc2d6caf6eb55ccf606770f24df2b5                                                NaN   
eb4e2aa0bf687227821b17cfcd5365e3  Bukit Batok Secondary School ITE College West ...   
acfb8e93139fe820996b27ee3c6bc9db  St Patrick&#039;s School, Singapore Class of 2...   
ea251951bd3c7667daf214e8efa92f4e                                                NaN   
f8f7b497ad8167535345bfc3d59d6aaa                                                NaN   

                                                                               work  \
row ID                                                                                
d0cc2d6caf6eb55ccf606770f24df2b5                                                NaN   
eb4e2aa0bf687227821b17cfcd5365e3                                                NaN   
acfb8e93139fe820996b27ee3c6bc9db                                                NaN   
ea251951bd3c7667daf214e8efa92f4e                                                NaN   
f8f7b497ad8167535345bfc3d59d6aaa  PT. Duta Marga Lestarindo September 2013 to pr...   

                                 relationship  education_level  \
row ID                                                           
d0cc2d6caf6eb55ccf606770f24df2b5          NaN              NaN   
eb4e2aa0bf687227821b17cfcd5365e3          NaN  college student   
acfb8e93139fe820996b27ee3c6bc9db       single  college student   
ea251951bd3c7667daf214e8efa92f4e          NaN              NaN   
f8f7b497ad8167535345bfc3d59d6aaa          NaN              NaN   

                                                    occupation  
row ID                                                          
d0cc2d6caf6eb55ccf606770f24df2b5                           NaN  
eb4e2aa0bf687227821b17cfcd5365e3                           NaN  
acfb8e93139fe820996b27ee3c6bc9db                           NaN  
ea251951bd3c7667daf214e8efa92f4e                           NaN  
f8f7b497ad8167535345bfc3d59d6aaa  archetecture and engineering

In [4]:
with open('featuresSingapore/Foursquare/descriptions/venueCategoriesFeaturesDescription', 'r') as f: print(f.read())


|-------------2 months (train)-------------|-----1 month (test)------|
|-------------------------3 months (train)---------------------------|-------------2 months (test)--------------|
|---------------------------------------------------5 months----------------------------------------------------|



In [5]:
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.cross_validation import train_test_split, cross_val_score, KFold
from sklearn.metrics import accuracy_score, average_precision_score
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC

In [6]:
foursquare5Months = pd.read_csv('featuresSingapore/Foursquare/venueCategoriesFeatures5Months.csv', index_col="_id")
instagramWhole = pd.read_csv('featuresSingapore/Instagram/imageConceptsFeatures.csv', index_col='_id')
twitterLDA50 = pd.read_csv('featuresSingapore/Twitter/LDA50Features.csv', index_col='_id')
twitterLIWC = pd.read_csv('featuresSingapore/Twitter/LIWCFeatures.csv', index_col='_id')
twitterManual = pd.read_csv('featuresSingapore/Twitter/manuallyDefinedTextFeatures.csv', index_col='_id')

In [7]:
facebookAnswers.gender

row ID
d0cc2d6caf6eb55ccf606770f24df2b5    female
eb4e2aa0bf687227821b17cfcd5365e3    female
acfb8e93139fe820996b27ee3c6bc9db      male
ea251951bd3c7667daf214e8efa92f4e    female
f8f7b497ad8167535345bfc3d59d6aaa    female
b6c4d3acf3f90ada2439e2f5668cdc07      male
1c1405656095a093c00d32d99d4fdbba      male
ebf87b9e2429bcf060e7db769c1367e6    female
9fc4094591ce99cab44bafbc9644dfe9    female
ec7980ca47e2864432025a78a71ba3cc    female
65b308410a4cbcd64426050b7b579345    female
6c209653fb1c78f2ceb117136e62e218      male
7e78bfe271ed998a4f3250a9a98043ce    female
40d8760be9ed3b6e806cc4966b567037      male
1070f07beea368659caf60ed3c668376      male
32ca67d052deeef4cfdcf6cb43093184    female
804a816175cf32491238ee72f99461da    female
188969e15d5201a0fe44834c25ea41bd      male
d17099a61d71e845dc0f4c025266f452    female
3d1997a734cb3c166032a312a63e06aa      male
8dd3595e30eed2ed2bce504a9f101d11      male
007e7e8169021679d9f95b2e5a9d17c4      male
972ee180226f610d2c2a7056e3b1ed19      male
f476

In [8]:
def binarize(arr): return np.where(arr == 'female', 1, 0)
facebookGender = facebookAnswers.gender.dropna().apply(binarize)
facebookGender.head()

row ID
d0cc2d6caf6eb55ccf606770f24df2b5    1
eb4e2aa0bf687227821b17cfcd5365e3    1
acfb8e93139fe820996b27ee3c6bc9db    0
ea251951bd3c7667daf214e8efa92f4e    1
f8f7b497ad8167535345bfc3d59d6aaa    1
Name: gender, dtype: int64

In [9]:
facebookReliableGender = facebookAnswers[["realAge", "gender"]].dropna(how="any").gender
facebookReliableGenderIndex = facebookReliableGender.index
for dataset in [foursquare5Months, instagramWhole, twitterLDA50, twitterLIWC, twitterManual]:
    facebookReliableGenderIndex = facebookReliableGenderIndex.intersection(dataset.index)
facebookReliableGender = facebookReliableGender.loc[facebookReliableGenderIndex].apply(binarize)
facebookReliableGender.head()

cfb7d89ba18299ffa6e462085db09b8b    0
e393c39e8095ff5aae0be885cda082a4    0
e975307e3661721e7405ec3719945e9e    1
8d09468583b985ff14d61f63cb637e9f    1
895bd593d8e0425c4f9cf52a82388f31    1
Name: gender, dtype: int64

In [10]:
facebookGenderOther = facebookGender.loc[facebookGender.index.difference(facebookReliableGender.index)]
facebookGenderOther.head()

0001fdb89ad0ffac6ab432b288b93e91    0
001e73b8bf12f18d96deb22dca3d5a17    0
003de0c9141ab503f3aa011c3c51cf45    1
005846808079907cec0694ce9685441b    1
006517a0c936d67827fae17d12bbeebf    1
Name: gender, dtype: int64

In [11]:
foursquare5MonthsGender = foursquare5Months.loc[facebookGender.index]
instagramGender = instagramWhole.loc[facebookGender.index]
twitterLDA50Gender = twitterLDA50.loc[facebookGender.index]
twitterLIWCGender = twitterLIWC.loc[facebookGender.index]
twitterManualGender = twitterManual.loc[facebookGender.index]
lateFusionGender = [
    (foursquare5MonthsGender, 140, foursquare5MonthsGender.categoryMentions.fillna(value=0)), 
    (instagramGender, 130, instagramGender.numberOfImages.fillna(value=0)), 
    (twitterLDA50Gender, 70, twitterManualGender.numberOfTweets.fillna(value=0)), 
    (twitterLIWCGender, 120, twitterManualGender.numberOfTweets.fillna(value=0)), 
    (twitterManualGender, 75, twitterManualGender.numberOfTweets.fillna(value=0))
]

In [12]:
genderCls = []
genderProbas = []
for dataset, nEstimators, count in lateFusionGender:
    dataOtherUsers = dataset.loc[facebookGenderOther.index].dropna()
    facebookLocal = facebookGenderOther.loc[dataOtherUsers.index]
    clf = RandomForestClassifier(n_estimators=nEstimators).fit(dataOtherUsers, facebookLocal)
    probas = clf.predict(dataset.fillna(value=0))
    genderCls.append(clf)
    genderProbas.append(probas)
genderProbas = np.array(genderProbas).T
genderProbas.shape

(4913, 5)

In [13]:
strengthsGender = []
for _, _, count in lateFusionGender:
    strengthsGender.append(count / count.mean())
strengthsGender = np.array(strengthsGender).T
strengthsGender.shape

(4913, 5)

In [15]:
def macro_accuracy(y, y_pred):
    res = [np.count_nonzero((y == cls) & (cls == y_pred)) / np.count_nonzero(y == cls) for cls in set(y)]
    return sum(res) / len(res)

In [17]:
accuraciesGender = []
def scoringCV(est, X, y): return macro_accuracy(y, est.predict(X))
for dataset, nEstimators, _ in lateFusionGender:
    dataOtherUsers = dataset.loc[facebookGenderOther.index].dropna()
    facebookLocal = facebookGenderOther.loc[dataOtherUsers.index]
    clf = RandomForestClassifier(n_estimators=nEstimators)
    cvs = cross_val_score(clf, dataOtherUsers, facebookLocal, cv=10, n_jobs=4, scoring=scoringCV)
    accuraciesGender.append(cvs.mean())
accuraciesGender = np.array(accuraciesGender)
accuraciesGender

array([ 0.66444537,  0.71442823,  0.75926138,  0.7045844 ,  0.67328651])

In [18]:
estimates = genderProbas * strengthsGender * accuraciesGender
for num, data in enumerate(lateFusionGender):
    data[0]['estimate'] = estimates[:,num]

In [19]:
estimatesTrain = np.array([data[0].estimate.loc[facebookGenderOther.index] for data in lateFusionGender]).T
estimatesTest = np.array([data[0].estimate.loc[facebookReliableGender.index] for data in lateFusionGender]).T
for dataset, _, _ in lateFusionGender:
    del dataset['estimate']
estimatesTrain.shape, estimatesTest.shape

((4602, 5), (311, 5))

In [20]:
logreg = LogisticRegression().fit(estimatesTrain, facebookGenderOther)
probas = logreg.predict(estimatesTest)
macro_accuracy(facebookReliableGender, probas)

0.6737429237429238

In [21]:
ageGroupClasses = sorted(set(facebookAnswers.ageGroup.dropna()))
ageGroupClasses = {name: num for num, name in enumerate(ageGroupClasses)}
ageGroupClasses

{'AGE10_20': 0, 'AGE20_30': 1, 'AGE30_40': 2, 'AGE40_50': 3, 'AGE50_INF': 4}

In [22]:
facebookAgeGroup = facebookAnswers.ageGroup.dropna().map(ageGroupClasses)
facebookAgeGroup.head()

row ID
acfb8e93139fe820996b27ee3c6bc9db    0
b6c4d3acf3f90ada2439e2f5668cdc07    1
1c1405656095a093c00d32d99d4fdbba    2
7e78bfe271ed998a4f3250a9a98043ce    0
1070f07beea368659caf60ed3c668376    1
Name: ageGroup, dtype: int64

In [23]:
facebookAgeGroupReliable = facebookAnswers[['realAge', 'ageGroup']].dropna(how='any').ageGroup.map(ageGroupClasses)
facebookAgeGroupReliableIndex = facebookAgeGroupReliable.index
for dataset in [foursquare5Months, instagramWhole, twitterLDA50, twitterLIWC, twitterManual]:
    facebookAgeGroupReliableIndex = facebookAgeGroupReliableIndex.intersection(dataset.index)
facebookAgeGroupReliable = facebookAgeGroupReliable.loc[facebookAgeGroupReliableIndex]
facebookAgeGroupReliable.head(20)

cfb7d89ba18299ffa6e462085db09b8b    0
e393c39e8095ff5aae0be885cda082a4    1
e975307e3661721e7405ec3719945e9e    1
8d09468583b985ff14d61f63cb637e9f    2
895bd593d8e0425c4f9cf52a82388f31    1
3e8cf61f8898a7c2432092f1345b84c4    0
85ee10e6bc63a3a6faac5abd4e2ae24d    1
3e87440810b221ec9d52056ea5fbc0cf    1
1069c60f75b4b758b519db2efd753b92    4
e916eb98ccc1dc8ae3499459d32ffb0c    0
200ebcc8836fe8db0ca505a42da6aeed    0
ea6c9638d021dbec6de3aaab20ef3087    0
28d236054ca8e17c21296a77d8af3e10    1
2e074716bba64c57d1fd003c64f560e6    1
cb516ddd8b9943d391b71c357d714061    1
d8efa1eaad69eac0048b32b85f311737    0
1070f07beea368659caf60ed3c668376    1
4361f6808bb41985b543444c550ddfcd    1
ce779c2bbb6f11d122ea2828fe17e9c5    1
b999b0cdf2cd2b455f2a4d2ea90335b3    1
Name: ageGroup, dtype: int64

In [24]:
facebookAgeGroupOther = facebookAgeGroup.loc[facebookAgeGroup.index.difference(facebookAgeGroupReliable.index)]
facebookAgeGroupOther.head(20)

0001fdb89ad0ffac6ab432b288b93e91    0
00726a917f3718d8708ea4acfead78ef    1
00858fa3e354f0c7b8b9d985b77c0980    0
0178af0adcb347a487fd38cc2993d3cc    1
0195953cbbe7eb68e58f0f8ad44c1139    1
01d243ee6d3dc4f65e4acaad0a5c5b0f    1
022748be87d354c2cc61341e034888b0    1
026591200b0faea85a8e154c3b91c9c3    0
0299e560adb729152412b2d58987f81a    1
02a942f7fcd783f227080f909021edbc    0
047bc95b152871a0d1eab6edfc1973d2    0
051138e8d07e68f9ec6ba8bbe6794767    0
05266544e92a7c66d0d3ba5d7f0ccab5    1
05348ee36a60a9853a66a66ca9742db2    0
055b74ea4fceb8581717b0a59c172711    2
05bfc9953b5a655f921e1bd34a103956    1
05dd9b807f9c169bf34045e5a83dd715    0
06548d2bd2c62775d6b6bdc37e93d155    1
06a73064049462fd9f5ce3140dae53eb    1
06fc091ad3df6266fd59a4f907d47772    1
Name: ageGroup, dtype: int64

In [25]:
foursquare5MonthsAgeGroup = foursquare5Months.loc[facebookAgeGroup.index]
instagramAgeGroup = instagramWhole.loc[facebookAgeGroup.index]
twitterLDA50AgeGroup = twitterLDA50.loc[facebookAgeGroup.index]
twitterLIWCAgeGroup = twitterLIWC.loc[facebookAgeGroup.index]
twitterManualAgeGroup = twitterManual.loc[facebookAgeGroup.index]
lateFusionAgeGroup = [
    (foursquare5MonthsAgeGroup, 140, foursquare5MonthsAgeGroup.categoryMentions.fillna(value=0)), 
    (instagramAgeGroup, 130, instagramAgeGroup.numberOfImages.fillna(value=0)), 
    (twitterLDA50AgeGroup, 70, twitterManualAgeGroup.numberOfTweets.fillna(value=0)), 
    (twitterLIWCAgeGroup, 120, twitterManualAgeGroup.numberOfTweets.fillna(value=0)), 
    (twitterManualAgeGroup, 75, twitterManualAgeGroup.numberOfTweets.fillna(value=0))
]

In [26]:
singleTrainTestAge = []
singleProbasAge = []
for dataset, nEstimators, count in lateFusionAgeGroup:
    dataOtherUsers = dataset.loc[facebookAgeGroupOther.index].dropna()
    facebookLocal = facebookAgeGroupOther.loc[dataOtherUsers.index]
    clf = RandomForestClassifier(n_estimators=nEstimators).fit(dataOtherUsers, facebookLocal)
    probas = clf.predict_proba(dataset.fillna(value=0))
    singleTrainTestAge.append(clf)
    singleProbasAge.append(probas)
singleProbasAge = np.array(singleProbasAge).swapaxes(0, 1)
singleProbasAge.shape

(1284, 5, 5)

In [27]:
accuraciesAge = []
def scoringCV(est, X, y): return macro_accuracy(y.values, est.predict(X))
for dataset, nEstimators, _ in lateFusionAgeGroup:
    dataOtherUsers = dataset.loc[facebookAgeGroupOther.index].dropna()
    facebookLocal = facebookAgeGroupOther.loc[dataOtherUsers.index]
    clf = RandomForestClassifier(n_estimators=nEstimators)
    cvs = cross_val_score(clf, dataOtherUsers, facebookLocal, cv=10, n_jobs=4, scoring=scoringCV)
    print(cvs)
    accuraciesAge.append(cvs.mean())
accuraciesAge = np.array(accuraciesAge)
accuraciesAge

/nix/store/n12nlyxbcqlz49ajdz87g5489xqzvr3g-python3.5-scikit-learn-0.17.1/lib/python3.5/site-packages/sklearn/cross_validation.py:516: Warning: The least populated class in y has only 3 members, which is too few. The minimum number of labels for any class cannot be less than n_folds=10.
  % (min_labels, self.n_folds)), Warning)


[ 0.26634146  0.24894309  0.25264929  0.33662742  0.32338099  0.32085786
  0.30004205  0.33452481  0.30109336  0.2487069 ]


/nix/store/n12nlyxbcqlz49ajdz87g5489xqzvr3g-python3.5-scikit-learn-0.17.1/lib/python3.5/site-packages/sklearn/cross_validation.py:516: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of labels for any class cannot be less than n_folds=10.
  % (min_labels, self.n_folds)), Warning)


[ 0.20871143  0.2699637   0.27726002  0.27236719  0.29077353  0.28098788
  0.24464119  0.28933398  0.26061776  0.26906371]


/nix/store/n12nlyxbcqlz49ajdz87g5489xqzvr3g-python3.5-scikit-learn-0.17.1/lib/python3.5/site-packages/sklearn/cross_validation.py:516: Warning: The least populated class in y has only 3 members, which is too few. The minimum number of labels for any class cannot be less than n_folds=10.
  % (min_labels, self.n_folds)), Warning)


[ 0.34097561  0.34178862  0.26846089  0.33662742  0.36648444  0.37338099
  0.35639193  0.33809924  0.37973087  0.30344828]


/nix/store/n12nlyxbcqlz49ajdz87g5489xqzvr3g-python3.5-scikit-learn-0.17.1/lib/python3.5/site-packages/sklearn/cross_validation.py:516: Warning: The least populated class in y has only 3 members, which is too few. The minimum number of labels for any class cannot be less than n_folds=10.
  % (min_labels, self.n_folds)), Warning)


[ 0.28634146  0.28406504  0.29063078  0.40239697  0.3244323   0.3647603
  0.32695542  0.34924306  0.33405172  0.31443966]


/nix/store/n12nlyxbcqlz49ajdz87g5489xqzvr3g-python3.5-scikit-learn-0.17.1/lib/python3.5/site-packages/sklearn/cross_validation.py:516: Warning: The least populated class in y has only 3 members, which is too few. The minimum number of labels for any class cannot be less than n_folds=10.
  % (min_labels, self.n_folds)), Warning)


[ 0.31737595  0.30442389  0.29688814  0.42468461  0.37947855  0.32780172
  0.29181034  0.33017241  0.32931034  0.27758621]


array([ 0.29331672,  0.26637204,  0.34053883,  0.32773167,  0.32795322])

In [28]:
strengthsAge = []
for _, _, count in lateFusionAgeGroup:
    strengthsAge.append(count / count.mean())
strengthsAge = np.expand_dims(np.array(strengthsAge).T, axis=2)
for i in range(1, 5):
    strengthsAge = np.append(strengthsAge, np.expand_dims(strengthsAge[:,:,0], axis=2), axis=2)
strengthsAge.shape

(1284, 5, 5)

In [29]:
estimatesAge = singleProbasAge * strengthsAge
for i in range(5):
    estimatesAge[:,:,i] *= accuraciesAge
for num, data in enumerate(lateFusionAgeGroup):
    for i in range(5):
        data[0]['estimate' + str(i)] = estimatesAge[:,num,i]
lateFusionAgeGroup[0][0].head()

/nix/store/n16wpgk37iwnl7f9c8g6c5c8szr4mk4k-python3.5-pandas-0.17.1/lib/python3.5/site-packages/pandas/core/format.py:2087: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e8).any()
/nix/store/n16wpgk37iwnl7f9c8g6c5c8szr4mk4k-python3.5-pandas-0.17.1/lib/python3.5/site-packages/pandas/core/format.py:2088: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) &
/nix/store/n16wpgk37iwnl7f9c8g6c5c8szr4mk4k-python3.5-pandas-0.17.1/lib/python3.5/site-packages/pandas/core/format.py:2089: RuntimeWarning: invalid value encountered in greater
  (abs_vals > 0)).any()


categoryMentions  f1  f2  f3  f4  f5  f6  \
row ID                                                                       
acfb8e93139fe820996b27ee3c6bc9db                53   0   0   0   0   0   0   
b6c4d3acf3f90ada2439e2f5668cdc07               NaN NaN NaN NaN NaN NaN NaN   
1c1405656095a093c00d32d99d4fdbba               609   0   0   0   0   0   0   
7e78bfe271ed998a4f3250a9a98043ce               NaN NaN NaN NaN NaN NaN NaN   
1070f07beea368659caf60ed3c668376               163   0   0   0   0   0   0   

                                  f7  f8  f9    ...      f760  f761  f762  \
row ID                                          ...                         
acfb8e93139fe820996b27ee3c6bc9db   0   0   0    ...         0     0     0   
b6c4d3acf3f90ada2439e2f5668cdc07 NaN NaN NaN    ...       NaN   NaN   NaN   
1c1405656095a093c00d32d99d4fdbba   0   0   0    ...         0     0     0   
7e78bfe271ed998a4f3250a9a98043ce NaN NaN NaN    ...       NaN   NaN   NaN   
1070f07beea368659caf60ed3c668376  27   0   1    ...         0     0     0   

                                  f763  f764  estimate0  estimate1  estimate2  \
row ID                                                                          
acfb8e93139fe820996b27ee3c6bc9db     0     0   0.306253   0.064474   0.005373   
b6c4d3acf3f90ada2439e2f5668cdc07   NaN   NaN   0.000000   0.000000   0.000000   
1c1405656095a093c00d32d99d4fdbba     0     0   2.870783   1.049534   0.339555   
7e78bfe271ed998a4f3250a9a98043ce   NaN   NaN   0.000000   0.000000   0.000000   
1070f07beea368659caf60ed3c668376     0     0   0.586605   0.528771   0.033048   

                                  estimate3  estimate4  
row ID                                                  
acfb8e93139fe820996b27ee3c6bc9db   0.000000   0.000000  
b6c4d3acf3f90ada2439e2f5668cdc07   0.000000   0.000000  
1c1405656095a093c00d32d99d4fdbba   0.030869   0.030869  
7e78bfe271ed998a4f3250a9a98043ce   0.000000   0.000000  
1070f07beea368659caf60ed3c668376   0.000000   0.008262  

[5 rows x 770 columns]

In [30]:
estimatesTrainAge = np.array([[data[0]['estimate{}'.format(i)].loc[facebookAgeGroupOther.index] for i in range(5)] for data in lateFusionAgeGroup])
estimatesTrainAge = estimatesTrainAge.swapaxes(1, 2).swapaxes(0, 1)
estimatesTestAge = np.array([[data[0]['estimate{}'.format(i)].loc[facebookAgeGroupReliable.index] for i in range(5)] for data in lateFusionAgeGroup])
estimatesTestAge = estimatesTestAge.swapaxes(1, 2).swapaxes(0, 1)
for dataset, _, _ in lateFusionAgeGroup:
    for i in range(5):
        del dataset['estimate' + str(i)]
estimatesTrainAge.shape, estimatesTestAge.shape

((973, 5, 5), (311, 5, 5))

In [31]:
logregs = []
for i in range(5):
    clsEstimate = estimatesTrainAge[:,:,i]
    trainAnswer = facebookAgeGroupOther.apply(lambda r: np.where(r == i, 1, 0))
    logreg = LogisticRegression().fit(clsEstimate, trainAnswer)
    print(logreg.coef_)
    logregs.append(logreg)

[[ 3.33719146  4.3143088   1.51875225  2.27003552  2.24965473]]
[[ 2.7906531   3.06922009  1.96127342 -0.07163897  0.85635865]]
[[ 3.4640693   4.07118054  0.95820555  1.04019794  1.32688085]]
[[ 1.86612436  1.71076615  1.12501652  1.06510072  1.13983763]]
[[ 1.71805569  0.33196543  0.45047569  0.45373726  0.41827644]]


In [32]:
testProbas = np.array([logreg.predict_proba(estimatesTestAge[:,:,i])[:,1] for i in range(5)]).T.argmax(axis=1)
macro_accuracy(facebookAgeGroupReliable, testProbas)

0.32947154471544715

In [33]:
wholeDataset = foursquare5Months
for i in [instagramWhole, twitterLDA50, twitterLIWC, twitterManual]:
    wholeDataset = wholeDataset.add(i, fill_value=0)
wholeDataset.fillna(method='ffill', inplace=True)
wholeDataset.head()

Dic  Qmarks  Sixltr  Unique     WC    WPS  \
_id                                                                             
0001fdb89ad0ffac6ab432b288b93e91  60.10    0.52   19.17   65.28    193  10.72   
0002c57d0324030950fb043fbdbd9131  29.52    0.12   18.16   57.20   1619  23.13   
0008f3e295599e6a9959658ba6175146  29.52    0.12   18.16   57.20   1619  23.13   
000ed674f6b42bc225cb97494b97717f  85.22    0.29   12.24    9.46  33444  45.26   
001159bbcef08a6072036c4ea8ad9106  85.22    0.29   12.24    9.46  33444  45.26   

                                  achieve  adverb  affect  anger  ...   \
_id                                                               ...    
0001fdb89ad0ffac6ab432b288b93e91     1.55    3.63    5.18   3.11  ...    
0002c57d0324030950fb043fbdbd9131     0.68    0.62    2.96   0.74  ...    
0008f3e295599e6a9959658ba6175146     0.68    0.62    2.96   0.74  ...    
000ed674f6b42bc225cb97494b97717f     1.27    7.19    8.64   1.14  ...    
001159bbcef08a6072036c4ea8ad9106     1.27    7.19    8.64   1.14  ...    

                                  topic_49   topic_5   topic_6       topic_7  \
_id                                                                            
0001fdb89ad0ffac6ab432b288b93e91  0.000250  0.001027  0.000572  5.600408e-05   
0002c57d0324030950fb043fbdbd9131  0.000019  0.076920  0.096644  4.322106e-06   
0008f3e295599e6a9959658ba6175146  0.000019  0.076920  0.096644  4.322106e-06   
000ed674f6b42bc225cb97494b97717f  0.000002  0.000007  0.000004  3.688820e-07   
001159bbcef08a6072036c4ea8ad9106  0.000002  0.000007  0.000004  3.688820e-07   

                                   topic_8   topic_9   verb    we  work   you  
_id                                                                            
0001fdb89ad0ffac6ab432b288b93e91  0.001000  0.010404   7.77  0.00  2.07  1.04  
0002c57d0324030950fb043fbdbd9131  0.005200  0.013244   3.95  0.19  1.24  0.25  
0008f3e295599e6a9959658ba6175146  0.005200  0.013244   3.95  0.19  1.24  0.25  
000ed674f6b42bc225cb97494b97717f  0.000069  0.000006  13.96  0.69  1.35  3.30  
001159bbcef08a6072036c4ea8ad9106  0.000069  0.000006  13.96  0.69  1.35  3.30  

[5 rows x 1900 columns]

In [34]:
genderWholeClf = RandomForestClassifier(n_estimators=sum(data[1] for data in lateFusionGender), n_jobs=4)
wholeDatasetGender = wholeDataset.loc[facebookGenderOther.index].dropna()
genderWholeClf.fit(wholeDatasetGender, facebookGenderOther.loc[wholeDatasetGender.index])
macro_accuracy(facebookReliableGender, genderWholeClf.predict(wholeDataset.loc[facebookReliableGender.index]))

0.7853604728604728

In [35]:
ageWholeClf = RandomForestClassifier(n_estimators=sum(data[1] for data in lateFusionGender), n_jobs=4)
wholeDatasetAge = wholeDataset.loc[facebookAgeGroupOther.index].dropna()
ageWholeClf.fit(wholeDatasetAge, facebookAgeGroupOther.loc[wholeDatasetAge.index])
macro_accuracy(facebookAgeGroupReliable, ageWholeClf.predict(wholeDataset.loc[facebookAgeGroupReliable.index]))

0.3069918699186992

In [36]:
import pickle

In [96]:
with open('genderWholeClf.dat', 'wb') as f: pickle.dump(genderWholeClf, f)
with open('ageTwitterLDAClf.dat', 'wb') as f: pickle.dump(singleTrainTestAge[2], f)

In [101]:
with open('genderWholeIndex.dat', 'wb') as f: pickle.dump(wholeDatasetGender.columns.values.tolist(), f)
with open('ageTwitterLDAIndex.dat', 'wb') as f: pickle.dump(twitterLDA50AgeGroup.columns.values.tolist(), f)

In [102]:
with open('ageGroups.dat', 'wb') as f: pickle.dump(ageGroupClasses, f)

In [39]:
from random import choice, randint

In [66]:
def increase_dim(w):
    w = np.expand_dims(w, axis=1)
    res = w.copy()
    for i in range(1, 5):
        res = np.append(res, w, axis=1)
    return res

wAge = np.array([1.] * 5)
wValues = (estimatesTrainAge * increase_dim(wAge)).mean(axis=1).argmax(axis=1)
wError = macro_accuracy(facebookAgeGroupOther, wValues)
dirs = set(range(5))
stepstep = 0.001
step = stepstep
for i in range(10000):
    crd = choice(list(dirs))
    dw = np.array([0 if i != crd else step * (randint(0,1) * 2 - 1) for i in range(5)])
    #dw = np.array([step * (randint(0,2) * 2 - 1) for i in range(5)])
    #dw = np.array([np.random.normal(0, step) for i in range(5)])
    #dw = np.array([0 if i != crd else np.random.normal(0, step) for i in range(5)])
    wdwValue = (estimatesTrainAge * increase_dim(wAge + dw)).mean(axis=1).argmax(axis=1)
    wdwError = macro_accuracy(facebookAgeGroupOther, wdwValue)
    if wdwError > wError:
        wAge = wAge + dw
        print(wAge, wError, wdwError)
        wError = wdwError
        dirs = set(range(5))
        step = stepstep
    else:
        dirs.remove(crd)
    if not dirs:
        step += stepstep
        dirs = set(range(5))
wValues = (estimatesTestAge * increase_dim(wAge)).mean(axis=1).argmax(axis=1)
wError = macro_accuracy(facebookAgeGroupReliable, wValues)
wError

[ 0.609  1.     1.     1.     1.   ] 0.9246804370603202 0.9250621164496332


0.32658536585365855

In [104]:
from http.client import HTTPConnection
import json

In [107]:
row20 = wholeDatasetGender.iloc[20]
request = json.dumps(row20.to_dict())
request

'{"f380": 0.0, "funct": 56.79, "i635": 2.550300609426839, "f698": 0.0, "f551": 0.0, "f8": 0.0, "f473": 0.0, "f373": 0.0, "i709": 2.9183958363489784, "f415": 0.0, "i120": 2.633542565719365, "f760": 0.0, "f542": 0.0, "i160": 2.558700214018398, "i830": 2.6520368690581604, "i514": 2.7280781796580515, "i496": 2.529130053925687, "i643": 2.732913426480232, "i725": 2.52711765528617, "f352": 0.0, "f618": 0.0, "f669": 0.0, "f667": 0.0, "i993": 2.621784218665903, "i714": 2.6528003449322117, "i968": 3.0971452886126696, "f100": 0.0, "i84": 2.906292649546688, "i152": 2.555544338427171, "i530": 3.033211160227826, "topic_11": 9.432671335521652e-07, "f378": 0.0, "i687": 2.765455936145059, "averageSentiScore": 0.1041708378307408, "i700": 2.4815765494957156, "i503": 2.25062816201716, "i604": 2.499845213807685, "f191": 0.0, "f55": 0.0, "i935": 3.004617540831592, "i671": 2.540709769552736, "f672": 0.0, "f368": 0.0, "i677": 2.77225306635629, "f600": 0.0, "i870": 2.63225954622019, "i232": 2.2976102375945566,

In [118]:
conn = HTTPConnection('dmitrytomp.cloudapp.net')
conn.request('POST', '/gender', body=request, headers={'Content-Type': 'application/json'})
print(conn.getresponse().read())
conn.close()

b'female'


In [115]:
genderWholeClf.predict(wholeDatasetGender.iloc[20])

/nix/store/n12nlyxbcqlz49ajdz87g5489xqzvr3g-python3.5-scikit-learn-0.17.1/lib/python3.5/site-packages/sklearn/utils/validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([1])

In [131]:
row21 = twitterLDA50AgeGroup.iloc[2]
request = json.dumps(row21.to_dict())
request

'{"topic_18": 7.77011415248817e-06, "topic_0": 4.017593234599746e-05, "topic_23": 5.5517370567170035e-06, "topic_21": 0.9801603446959468, "topic_3": 1.875844893349741e-06, "topic_41": 7.360477495865779e-05, "topic_25": 1.1019001860758473e-05, "topic_47": 1.2846673883007625e-05, "topic_6": 3.2092832394533235e-05, "topic_27": 0.0002242587142664439, "topic_34": 1.917157335225105e-05, "topic_12": 3.710298996978781e-05, "topic_39": 3.326717155484388e-06, "topic_4": 0.0018388223124091835, "topic_13": 1.2783181352793733e-05, "topic_29": 1.191229502015012e-05, "topic_19": 0.00014840313250651533, "topic_49": 0.0005460734637457872, "topic_45": 3.831362617573646e-05, "topic_38": 7.500944232015382e-06, "topic_37": 0.00013084105020125957, "topic_40": 3.177987073415129e-05, "topic_10": 2.2809038874771716e-05, "topic_46": 6.2561950541505e-05, "topic_44": 1.0171679646839977e-05, "topic_43": 4.0553856921446036e-05, "topic_24": 1.347896572011143e-05, "topic_1": 0.004899390829405058, "topic_14": 1.596826

In [136]:
conn = HTTPConnection('dmitrytomp.cloudapp.net')
conn.request('POST', '/age', body=request, headers={'Content-Type': 'application/json'})
print(conn.getresponse().read())
conn.close()

b'AGE20_30'


In [133]:
singleTrainTestAge[2].predict(row21)

/nix/store/n12nlyxbcqlz49ajdz87g5489xqzvr3g-python3.5-scikit-learn-0.17.1/lib/python3.5/site-packages/sklearn/utils/validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([1])

In [130]:
twitterLDA50AgeGroup.iloc[2]

topic_0     4.017593e-05
topic_1     4.899391e-03
topic_2     1.644938e-05
topic_3     1.875845e-06
topic_4     1.838822e-03
topic_5     5.761485e-05
topic_6     3.209283e-05
topic_7     3.142382e-06
topic_8     5.612468e-05
topic_9     5.171898e-05
topic_10    2.280904e-05
topic_11    2.227586e-06
topic_12    3.710299e-05
topic_13    1.278318e-05
topic_14    1.596827e-05
topic_15    5.072843e-05
topic_16    1.229517e-04
topic_17    6.417313e-04
topic_18    7.770114e-06
topic_19    1.484031e-04
topic_20    1.549956e-06
topic_21    9.801603e-01
topic_22    1.438033e-05
topic_23    5.551737e-06
topic_24    1.347897e-05
topic_25    1.101900e-05
topic_26    1.889401e-05
topic_27    2.242587e-04
topic_28    3.761608e-05
topic_29    1.191230e-05
topic_30    4.510958e-07
topic_31    3.120615e-05
topic_32    5.187231e-06
topic_33    1.013191e-02
topic_34    1.917157e-05
topic_35    7.865662e-05
topic_36    4.225569e-05
topic_37    1.308411e-04
topic_38    7.500944e-06
topic_39    3.326717e-06
